nome= (input('digite seu nome completo:')).strip()
div = nome.split()
junt = ''.join(div)
print(f'seu nome em letras maiusculas:{nome.upper()}')
print(f'seu nome em letras minusculas:{nome.lower()}')
print(f'sem considerar os espaços,seu nome tem {len(junt)} letras')
print(f'seu primeiro nome tem {len(div[0])} letras')
