n1 =input('digite algo:')
print(type(n1))
print('É UM NUMÉRICO?\n{}'.format(n1.isnumeric()))
print('É ALFABÉTICO?\n{}'.format(n1.isalpha()))
print('É ALFANUMÉRICO?\n{}'.format(n1.isalnum()))
print('ESTA EM LETRA MAIÚSCULA?\n{}'.format(n1.isupper()))
print('ESTA EM LETRA MINÚSCULA?\n{}'.format(n1.islower()))
print('É DECIMAL?[0,9]\n{}'.format(n1.isdecimal()))
print('É SOMENTE ESPAÇO?\n{}'.format(n1.isspace()))
print('SÃO DIGITOS?\n{}'.format(n1.isdigit()))
print('ESTA CAPITALIZADA?\n{}'.format(n1.istitle()))
